controllers:
    resource: ../src/Controller/
    type: attribute

spa:
    path: /{vueRouting}
    controller: App\Controller\AppController::index
    requirements:
        vueRouting: "^(?!api).+"
    defaults:
        vueRouting: null